spring.application.name=token1
server.port=8084

#spring.security.user.name=vasu
#spring.security.user.password=vasu

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/token1
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.layout=BaseLayout
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.path=/api-docs